name: bot
description: bot
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  nyxx: ^6.6.1
  nyxx_commands: ^6.0.3
  web_socket_channel: ^2.1.0
  dotenv: ^4.2.0
  get_it: ^8.0.3
  uuid: ^4.5.1
  intl: ^0.18.1
  sqlite3: ^2.7.5
  sqflite_common_ffi: ^2.3.0
  synchronized: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
